#!/usr/bin/env perl
#Fix loci that have been defined with reverse-complemented alleles.
#These have commonly been generated by SeqSphere+.
#Written by Keith Jolley
#Copyright (c) 2026, University of Oxford
#E-mail: keith.jolley@biology.ox.ac.uk
#Version: 20260912
use strict;
use warnings;
use 5.010;
###########Local configuration################################
use constant {
	CONFIG_DIR       => '/etc/bigsdb',
	LIB_DIR          => '/usr/local/lib',
	DBASE_CONFIG_DIR => '/etc/bigsdb/dbases',
};
#######End Local configuration################################
use lib (LIB_DIR);
use BIGSdb::Offline::Script;
use BIGSdb::Constants qw(LOG_TO_SCREEN);
use Term::Cap;
use Getopt::Long qw(:config no_ignore_case);

#Direct all library logging calls to screen
my $log_conf = LOG_TO_SCREEN;
Log::Log4perl->init( \$log_conf );
my $logger = Log::Log4perl::get_logger('BIGSdb.Script');

my %opts;
GetOptions(
	'curator=i'        => \$opts{'curator_id'},
	'd|database=s'     => \$opts{'d'},
	'fix'              => \$opts{'fix'},
	'help'             => \$opts{'help'},
	'l|loci=s'         => \$opts{'l'},
	'L|exclude_loci=s' => \$opts{'L'},
	'log_file=s'       => \$opts{'log_file'},
	'R|locus_regex=s'  => \$opts{'R'},
	's|schemes=s'      => \$opts{'s'}
);
$opts{'log_file'} //= 'log.txt';
if ( $opts{'help'} ) {
	show_help();
	exit;
}
if ( !$opts{'d'} ) {
	say 'Usage: fix_revseq_loci.pl --database [DB_CONFIG]';
	exit;
}
my $script = BIGSdb::Offline::Script->new(
	{
		config_dir       => CONFIG_DIR,
		lib_dir          => LIB_DIR,
		dbase_config_dir => DBASE_CONFIG_DIR,
		instance         => $opts{'d'},
		options          => { no_user_db_needed => 1, %opts },
		logger           => $logger,
	}
);

if ( ( $script->{'system'}->{'dbtype'} // q() ) ne 'sequences' ) {
	die "Script can only be run against a seqdef database.\n";
}
main();
undef $script;

sub main {
	my $loci = $script->get_selected_loci;
	die "No valid loci selected.\n" if !@$loci;
	my $reverse_complemented = [];
	my $correct_loci         = [];
	my $loci_with_problems   = [];
	foreach my $locus (@$loci) {
		print qq(Checking $locus:\t);
		my $locus_info = $script->{'datastore'}->get_locus_info($locus);
		my $order      = $locus_info->{'allele_id_format'} eq 'integer' ? 'CAST (allele_id AS int)' : 'allele_id';
		my $alleles    = $script->{'datastore'}->run_query( "SELECT * FROM sequences WHERE locus=? ORDER BY $order",
			$locus, { fetch => 'all_arrayref', slice => {} } );
		next if !@$alleles;
		my $all_ok     = 1;
		my $all_revseq = 1;
		foreach my $allele (@$alleles) {
			my $check_cds = BIGSdb::Utils::is_complete_cds( $allele->{'sequence'},
				{ start_codons => [qw(ATG GTG TTG CTG ATT ATC ATA)] } );
			if ( $check_cds->{'cds'} ) {
				$all_revseq = 0;
				next;
			}
			$all_ok = 0;

			my $revseq = BIGSdb::Utils::reverse_complement( $allele->{'sequence'} );
			my $check_reverse_cds =
			  BIGSdb::Utils::is_complete_cds( $revseq, { start_codons => [qw(ATG GTG TTG CTG ATT ATC ATA)] } );
			if ( !$check_reverse_cds->{'cds'} ) {
				$all_revseq = 0;
				next;
			}

		}
		my $status;

		if ($all_revseq) {
			$status = 'all reversed';
			push @$reverse_complemented, $locus;
		} elsif ($all_ok) {
			$status = 'all ok';
			push @$correct_loci, $locus;
		} else {
			$status = "non valid alleles";
			push @$loci_with_problems, $locus;
		}

		if ( $all_revseq && $opts{'fix'} ) {
			fix($locus);
			$status .= q( - FIXED!);
		}
		say $status;
	}
	if (@$reverse_complemented) {
		append_log("Reverse-complemented:");
		append_log($_) foreach @$reverse_complemented;
		append_log();
	}
	if (@$correct_loci) {
		append_log("Normal CDS:");
		append_log($_) foreach @$correct_loci;
		append_log();
	}
	if (@$loci_with_problems) {
		append_log("Loci with some invalid alleles:");
		append_log($_) foreach @$loci_with_problems;
		append_log();
	}
}

sub fix {
	my ($locus)    = @_;
	my $locus_info = $script->{'datastore'}->get_locus_info($locus);
	my $order      = $locus_info->{'allele_id_format'} eq 'integer' ? 'CAST (allele_id AS int)' : 'allele_id';
	my $alleles    = $script->{'datastore'}->run_query( "SELECT * FROM sequences WHERE locus=? ORDER BY $order",
		$locus, { fetch => 'all_arrayref', slice => {} } );
	return if !@$alleles;
	eval {
		foreach my $allele (@$alleles) {
			my $revseq  = BIGSdb::Utils::reverse_complement( $allele->{'sequence'} );
			my $curator = $opts{'curator'} // $allele->{'curator'};

			$script->{'db'}
			  ->do( 'UPDATE sequences SET (sequence,curator,datestamp)=(?,?,?) WHERE (locus,allele_id)=(?,?)',
				undef, $revseq, $curator, 'now', $locus, $allele->{'allele_id'} );

		}
	};
	if ($@) {
		$script->{'db'}->rollback;
		die "Cannot fix locus $locus: $@\n";
	}
	$script->{'db'}->commit;
}

sub append_log {
	my ($line) = @_;
	state $first_call = 1;
	my $open_or_append = $first_call ? '>' : '>>';
	open( my $log_fh, $open_or_append, $opts{'log_file'} ) or die "Cannot open $opts{'log_file'} for appending.\n";
	$line //= q();
	say $log_fh $line;
	close $log_fh;
	$first_call = 0;
	return;

}

sub show_help {
	my $termios = POSIX::Termios->new;
	$termios->getattr;
	my $ospeed = $termios->getospeed;
	my $t      = Tgetent Term::Cap { TERM => undef, OSPEED => $ospeed };
	my ( $norm, $bold, $under ) = map { $t->Tputs( $_, 1 ) } qw/me md us/;
	say << "HELP";
${bold}NAME$norm
    ${bold}fix_revseq_loci.pl$norm - Fix loci that have been defined with 
    reverse-complemented alleles.
    
${bold}SYNOPSIS$norm
    ${bold}fix_revseq_loci.pl$norm ${bold}--database ${under}DB_CONFIG${norm}

${bold}OPTIONS$norm

${bold}--curator$norm ${under}CURATOR ID$norm
    Curator id to use for updates. By default -1 is used - there should be an
    autodefiner account set with this id number.
    
${bold}--database$norm ${under}DATABASE CONFIG$norm
    Database configuration name. This must be a sequence definition database.
    
${bold}--exclude_loci, -L$norm ${under}LIST$norm
    Comma-separated list of loci to exclude
    
${bold}--fix$norm
    Update database with reverse-complemented sequence if necessary.
    
${bold}--loci, -l$norm ${under}LIST$norm
    Comma-separated list of loci to scan (ignored if -s used).
    
${bold}--locus_regex -R$norm ${under}REGEX$norm
    Regex for locus names.
    
${bold}--log_file$norm ${under}LOGFILE$norm
    Path and filename for output log. Default is log.txt.
    
${bold}--schemes, -s$norm ${under}LIST$norm
    Comma-separated list of scheme loci to scan.
    
HELP
	return;
}
